-- MySQL Script generated by MySQL Workbench
-- Sun May  6 10:30:24 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ChatDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ChatDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ChatDB` DEFAULT CHARACTER SET utf8 ;
USE `ChatDB` ;

-- -----------------------------------------------------
-- Table `ChatDB`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ChatDB`.`users` (
  `id_user` INT NOT NULL,
  `nick` VARCHAR(45) NOT NULL,
  `statusText` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `login_UNIQUE` (`nick` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ChatDB`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ChatDB`.`messages` (
  `id_message` INT NOT NULL,
  `message` LONGTEXT NOT NULL,
  `date_of_message` DATETIME NOT NULL,
  `identifier` VARCHAR(200) NULL,
  `from` VARCHAR(45) NULL,
  `to` VARCHAR(45) NULL,
  PRIMARY KEY (`id_message`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
